# Generated by Django 5.0.6 on 2024-07-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('usn', models.CharField(max_length=10)),
                ('subject_code', models.CharField(max_length=7)),
                ('attendance', models.FloatField()),
            ],
        ),
    ]
