# Generated by Django 5.0.6 on 2024-07-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('student_name', models.CharField(max_length=100)),
                ('student_usn', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
