# Generated by Django 5.0.6 on 2024-07-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0003_studentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='name',
            field=models.CharField(default='Wazeera Khan', max_length=100),
            preserve_default=False,
        ),
    ]
