# Generated by Django 5.0.6 on 2024-07-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0004_studentdetail_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=8)),
                ('attendance_percentage', models.FloatField()),
                ('student_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptmapp.studentdetail')),
            ],
        ),
    ]
