# Generated by Django 5.0.6 on 2024-07-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0007_alter_cie_cie1_alter_cie_cie2_alter_cie_cie3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cie',
            name='cie3',
        ),
        migrations.AlterField(
            model_name='cie',
            name='cie1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cie',
            name='cie2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
