# Generated by Django 5.0.6 on 2024-07-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0014_attendanceresponse_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ptmapp.userprofile'),
        ),
    ]
