# Generated by Django 5.0.6 on 2024-07-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0020_studentdetail_user_alter_notification_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='AttendanceResponse',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
