# Generated by Django 5.0.6 on 2024-07-14 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0023_parentresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='notification',
            name='meeting_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ptmapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='AttendanceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.BooleanField()),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptmapp.notification')),
                ('student_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptmapp.studentdetail')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='attendees',
            field=models.ManyToManyField(through='ptmapp.AttendanceResponse', to='ptmapp.studentdetail'),
        ),
        migrations.DeleteModel(
            name='ParentResponse',
        ),
    ]
