# Generated by Django 5.0.6 on 2024-07-14 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0024_remove_notification_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='teacher',
        ),
        migrations.CreateModel(
            name='ptmNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meeting_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ptmapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ParentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.BooleanField()),
                ('student_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptmapp.studentdetail')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptmapp.ptmnotification')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceResponse',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
