# Generated by Django 5.0.6 on 2024-07-14 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0025_remove_notification_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentresponse',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ptmapp.ptmnotification'),
        ),
        migrations.AlterField(
            model_name='parentresponse',
            name='student_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ptmapp.studentdetail'),
        ),
    ]
