# Generated by Django 5.0.6 on 2024-07-14 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapp', '0026_alter_parentresponse_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentresponse',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptmapp.ptmnotification'),
        ),
    ]
